// tesmiolauncher - starts the game with tesmioloader.dll injected.
//
// The game is created suspended, the DLL is loaded into it via a remote thread,
// and only then is the main thread released. Injecting before the game runs a
// single instruction means the import table is already resolved (the loader runs
// on our remote thread) while no game code has executed yet, so every file the
// game opens passes through the gate.
//
// Nothing in the game folder is modified. Steam's file verification stays happy.
//
// Two things sit around that injection.
//
// FINDING THE GAME. The old default was a single path, <self>\..\..\SOVIET64.exe,
// which is right only when tesmioloader\build\ is inside the game folder. Four
// strategies now run in order - an explicit --game, the path the window last
// saved into tesmioloader.ini, a walk up the tree from the launcher looking one
// folder deep at every level, and Steam's own library list via the registry and
// appmanifest_784150.acf. A folder is only believed to be the install when
// SOVIET64.exe is in it beside C3DDLL64.dll or media_soviet: the exe name alone
// would also match a stray copy in someone's Downloads, and injecting into that
// fails in a way nobody can read.
//
// THE WINDOW. One checkbox per DLL in plugins\, written to the [plugins] section
// of tesmioloader.ini. The loader reads that section per DLL, so unchecking one
// leaves the file where it is and simply never loads it - nothing is renamed or
// deleted, which is what makes the choice reversible from either side. --nogui
// skips the window entirely and behaves exactly as this program did before.
//
// The checkboxes sit in a scrolling two-column list rather than one column the
// window grows to fit: the loader takes up to 32 plugins and a column of 32 is
// taller than a laptop screen, at which point Launch is off the bottom edge and
// unreachable. The list is its own child window with WS_VSCROLL - see
// "the plugin list" below.
//
// Every checkbox also says whose signature the DLL carries. A plugin signed by
// tools\signing\tsmsign.exe verifies against the public key embedded in this
// binary and is labelled "signed by Tesmio"; anything without a valid
// <name>.dll.sig is labelled "not from Tesmio", and a signature that no longer
// matches the bytes is red. A mark is all it is - foreign plugins still load,
// because blocking them is the loader's business, not the window's.
//
// THE VERSION GATE. Every address the loader and its plugins patch belongs to
// a build of the game, and the project was originally written against v1.1.1.7.
// A regular-branch content update then shipped v1.1.1.9 - a new PE build (its
// own TimeDateStamp) but, per the update notes, no change to game code, only to
// content - so tesmioloader b0.3.6 recognises both builds rather than dropping
// the old one: kSupportedVersions below is a table, not a single constant, and
// either build reads as GV_OK. A patch site still verifies its own bytes before
// it writes, so if a future update ever does move code, the affected hooks
// refuse rather than corrupt the process - but that is a dozen separate
// refusals in a log file nobody reads, after the game is already up. The
// launcher checks the version once, before the process exists, and says so in
// the window in plain words. A game that is not a supported version is not
// launched at all; `version_check = 0` in tesmioloader.ini, or --ignore-version,
// turns the refusal back into a warning for whoever is porting to a new build.
//
// SOVIET64.exe carries no VERSIONINFO resource - FileVersion is 0.0.0.0 - so
// there is nothing to ask the shell for. The version is read out of the only
// place the game itself keeps it: the four numbers it formats its own main-menu
// line from. See ReadGameVersion.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <shellapi.h>           // WIN32_LEAN_AND_MEAN leaves this one out
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// For TSM_API_VERSION, TSM_EXPORT_APIVERSION and TsmPluginApiVersionFn - the
// launcher probes the same export the loader checks in LoadPlugins, so both
// sides read one definition and can never disagree about what "compatible"
// means.
#include "tesmio_api.h"

// The signature check. The format and the CNG primitives live in
// tesmio_sign.h; the public half of Tesmio's key pair is tesmio_pubkey.h,
// generated by tools\signing\tsmsign.exe. A plugin with a valid
// <name>.dll.sig beside its DLL is the exact bytes Tesmio built - everything
// else is marked in the window rather than trusted, because provenance is the
// one claim a third-party build cannot forge without the private key.
//
// Both headers are OPTIONAL: a source drop without the signing machinery
// still compiles, into a launcher that simply never mentions signatures -
// CheckPluginSignature reports TSM_SIG_NONE for everything and PluginSigNote
// stays empty, so no plugin is accused of being "not from Tesmio" by a build
// that could not have recognised a Tesmio signature anyway.
#if defined(__has_include)
#  if __has_include("tesmio_sign.h") && __has_include("tesmio_pubkey.h")
#    define TSM_LAUNCHER_SIGNING 1
#    include "tesmio_sign.h"
#    include "tesmio_pubkey.h"
#  endif
#endif
#ifndef TSM_LAUNCHER_SIGNING
#  define TSM_LAUNCHER_SIGNING 0
#endif

#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "comdlg32.lib")
#pragma comment(lib, "shell32.lib")

// Themed controls without a resource script: build.bat compiles one .cpp per
// binary and a .rc would put a second tool in that chain. This is the same
// dependency an .rc-embedded manifest would declare.
#pragma comment(linker, "\"/MANIFESTDEPENDENCY:type='win32' "                  \
                        "name='Microsoft.Windows.Common-Controls' "            \
                        "version='6.0.0.0' processorArchitecture='*' "         \
                        "publicKeyToken='6595b64144ccf1df' language='*'\"")

#define GAME_EXE        L"SOVIET64.exe"
#define GAME_ENGINE     L"C3DDLL64.dll"     // ships with the game and nothing else
#define GAME_MEDIA      L"media_soviet"
#define STEAM_APPID     L"784150"
#define LOADER_DLL      L"tesmioloader.dll"
#define LOADER_INI      L"tesmioloader.ini"

#define MAX_PLUGINS     32                  // mirrors the loader's own cap
#define WALK_UP_LEVELS  8

// The build of the game this project is written against. Every hard-coded rva
// in the loader and in every plugin belongs to it and was re-derived for it in
// b0.3.6; docs/02-findings.md describes it.
//
// A table rather than one constant, because the port off v1.1.1.7 proved the
// shape is worth keeping: adding a build is one row plus a pass of the address
// scanner. v1.1.1.7 was dropped deliberately - its addresses no longer exist
// anywhere in this tree, so accepting it would only inject into a game none of
// the patches fit.
//
// Two independent facts about the same exe, and they answer different
// questions. The four numbers are what the game prints in its own main menu and
// what a player calls "the version". The PE TimeDateStamp is the build: a
// hotfix that leaves the numbers alone still moves code, and the stamp is the
// only thing that notices.
//
// This is compiled in rather than configurable on purpose. It is not a
// preference - it is a statement about which addresses this binary was built
// with, and a config key that let it be changed would only produce a launcher
// that injects confidently into a game it cannot patch.
struct SupportedGameVersion
{
    int            v[4];
    unsigned       stamp;
    const wchar_t* text;
};

static const SupportedGameVersion kSupportedVersions[] = {
    { { 1, 1, 1, 9 }, 0x6A3EB6ADu, L"1.1.1.9" },  // 2026-06-26 17:28:13 UTC
};
#define GAME_VER_COUNT (sizeof(kSupportedVersions) / sizeof(kSupportedVersions[0]))

// The text every message that used to say "v" GAME_VER_TEXT now says instead -
// built on first use from the table above so a third entry never needs a
// second edit anywhere else in this file. "v1.1.1.7 or v1.1.1.9".
static const wchar_t* SupportedVersionsText()
{
    static wchar_t text[64];
    if (!text[0])
    {
        wchar_t* out = text;
        size_t   left = _countof(text);
        for (size_t i = 0; i < GAME_VER_COUNT && left > 2; i++)
        {
            int n = _snwprintf_s(out, left, _TRUNCATE, i == 0 ? L"v%s" : L" or v%s",
                                 kSupportedVersions[i].text);
            if (n < 0) break;
            out += n; left -= (size_t)n;
        }
    }
    return text;
}

// The ICON resource in src\tesmiolauncher.rc - logo.ico, generated from
// logo.png, ten sizes. Windows takes the lowest-numbered ICON as the
// executable's application icon, which is why it is 1; the same resource is
// loaded by hand below for the window itself, because a window's icon comes
// from its class and not from the exe.
#define IDI_TSM_LOGO    1

// ---------------------------------------------------------------- messages
//
// Everything this program has to say goes through Msg: to the console when one
// is attached, to the status line when the window is up, and always into a
// buffer, because a failure with the window open has to be readable after the
// fact rather than only in a console nobody sees.

static bool    g_console;
static HWND    g_status;
static wchar_t g_log[8192];

// A /SUBSYSTEM:WINDOWS process gets no console of its own, which is the point -
// double-clicking it must not open one behind the window. Two ways it can still
// have somewhere to print, and the order matters:
//
//   an inherited handle, when the caller redirected stdout to a pipe or a file.
//   The CRT has already wired the streams to it and reopening CONOUT$ would
//   write past the redirection to a console the caller is not reading.
//
//   the parent's console, when it was started from a terminal with no
//   redirection. Nothing is inherited, so the streams have to be pointed at it.
static void OpenConsole()
{
    HANDLE out = GetStdHandle(STD_OUTPUT_HANDLE);
    if (out && out != INVALID_HANDLE_VALUE) { g_console = true; return; }

    if (!AttachConsole(ATTACH_PARENT_PROCESS)) return;

    FILE* f = NULL;
    freopen_s(&f, "CONOUT$", "w", stdout);
    freopen_s(&f, "CONOUT$", "w", stderr);
    g_console = true;
}

static void Msg(const wchar_t* fmt, ...)
{
    wchar_t line[1024];
    va_list ap;
    va_start(ap, fmt);
    _vsnwprintf_s(line, _countof(line), _TRUNCATE, fmt, ap);
    va_end(ap);

    if (g_console) fwprintf(stdout, L"[tesmiolauncher] %s\n", line);

    size_t used = wcslen(g_log);
    _snwprintf_s(g_log + used, _countof(g_log) - used, _TRUNCATE, L"%s\r\n", line);

    if (g_status) SetWindowTextW(g_status, line);
}

static void Fail(const wchar_t* what)
{
    DWORD e = GetLastError();
    wchar_t* text = NULL;
    FormatMessageW(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM |
                   FORMAT_MESSAGE_IGNORE_INSERTS,
                   NULL, e, 0, (wchar_t*)&text, 0, NULL);
    if (text) for (wchar_t* p = text; *p; p++) if (*p == L'\r' || *p == L'\n') *p = L' ';
    Msg(L"%s failed (%lu): %s", what, e, text ? text : L"?");
    if (text) LocalFree(text);
}

// ---------------------------------------------------------------- paths

static bool Exists(const wchar_t* p)
{
    DWORD a = GetFileAttributesW(p);
    return a != INVALID_FILE_ATTRIBUTES && !(a & FILE_ATTRIBUTE_DIRECTORY);
}

static bool DirExists(const wchar_t* p)
{
    DWORD a = GetFileAttributesW(p);
    return a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_DIRECTORY);
}

static void Join(wchar_t* out, size_t n, const wchar_t* dir, const wchar_t* leaf)
{
    size_t len = wcslen(dir);
    bool slash = len > 0 && (dir[len - 1] == L'\\' || dir[len - 1] == L'/');
    _snwprintf_s(out, n, _TRUNCATE, slash ? L"%s%s" : L"%s\\%s", dir, leaf);
}

// Strips the last component in place. False when there was nothing left to
// strip, which is what ends the walk up the tree. The root keeps its slash and
// is reported as a successful step, so it gets looked at once before the walk
// stops - a game unpacked straight into D:\ is unusual but not impossible.
static bool ToParent(wchar_t* p)
{
    wchar_t* s = wcsrchr(p, L'\\');
    if (!s) return false;

    if (s == p || (s == p + 2 && p[1] == L':'))      // "\x" or "C:\x"
    {
        if (!s[1]) return false;                     // already "\" or "C:\"
        s[1] = 0;
        return true;
    }

    *s = 0;
    return true;
}

// ---------------------------------------------------------------- finding the game

// SOVIET64.exe beside something only the install has. Two acceptable witnesses
// because a Steam verify can be mid-flight and because ModelViewer users
// sometimes have a folder with the exe and no media.
static bool IsGameDir(const wchar_t* dir, wchar_t* outExe, size_t n)
{
    wchar_t exe[MAX_PATH], witness[MAX_PATH];
    Join(exe, _countof(exe), dir, GAME_EXE);
    if (!Exists(exe)) return false;

    Join(witness, _countof(witness), dir, GAME_ENGINE);
    if (!Exists(witness))
    {
        Join(witness, _countof(witness), dir, GAME_MEDIA);
        if (!DirExists(witness)) return false;
    }

    wcscpy_s(outExe, n, exe);
    return true;
}

// One level down, every child. The case this catches is the folder having been
// put in the wrong place rather than named oddly - tesmioloader next to
// SovietRepublic instead of inside it - so one level is enough and a deep
// recursive scan would only be a way to walk someone's whole drive.
static bool FindInChildren(const wchar_t* dir, wchar_t* out, size_t n)
{
    wchar_t pattern[MAX_PATH];
    Join(pattern, _countof(pattern), dir, L"*");

    WIN32_FIND_DATAW fd;
    HANDLE h = FindFirstFileW(pattern, &fd);
    if (h == INVALID_HANDLE_VALUE) return false;

    bool found = false;
    do
    {
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) continue;
        if (fd.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) continue;
        if (fd.cFileName[0] == L'.') continue;

        wchar_t child[MAX_PATH];
        Join(child, _countof(child), dir, fd.cFileName);
        if (IsGameDir(child, out, n)) { found = true; break; }
    } while (FindNextFileW(h, &fd));

    FindClose(h);
    return found;
}

static bool FindNearSelf(const wchar_t* selfDir, wchar_t* out, size_t n)
{
    wchar_t dir[MAX_PATH];
    wcscpy_s(dir, _countof(dir), selfDir);

    for (int up = 0; up <= WALK_UP_LEVELS; up++)
    {
        if (IsGameDir(dir, out, n))      return true;
        if (FindInChildren(dir, out, n)) return true;
        if (!ToParent(dir))              break;
    }
    return false;
}

// --- Steam ---------------------------------------------------------------

static char* ReadAll(const wchar_t* path)
{
    HANDLE h = CreateFileW(path, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE,
                           NULL, OPEN_EXISTING, 0, NULL);
    if (h == INVALID_HANDLE_VALUE) return NULL;

    DWORD size = GetFileSize(h, NULL);
    if (size == INVALID_FILE_SIZE || size > (4u << 20)) { CloseHandle(h); return NULL; }

    char* buf = (char*)malloc(size + 1);
    DWORD got = 0;
    if (!buf || !ReadFile(h, buf, size, &got, NULL)) { free(buf); CloseHandle(h); return NULL; }

    buf[got] = 0;
    CloseHandle(h);
    return buf;
}

// A vdf line is  "key"<tabs>"value"  and the only escape Steam writes inside a
// quoted token is a doubled backslash, so unescaping is one character wide.
// Returns the text just past the closing quote of the value, so a caller can
// keep scanning for the next one.
static const char* VdfValue(const char* pastKey, char* out, size_t n)
{
    const char* p = pastKey;
    while (*p && *p != '"' && *p != '\n') p++;
    if (*p != '"') return NULL;
    p++;

    size_t w = 0;
    while (*p && *p != '"')
    {
        char c = *p++;
        if (c == '\\' && *p) c = *p++;
        if (w + 1 < n) out[w++] = c;
    }
    if (*p != '"') return NULL;

    out[w] = 0;
    return p + 1;
}

static void Widen(const char* in, wchar_t* out, int n)
{
    if (MultiByteToWideChar(CP_UTF8, 0, in, -1, out, n) == 0)
        MultiByteToWideChar(CP_ACP, 0, in, -1, out, n);
}

// The library holding the game is whichever one has its app manifest, so the
// libraries only have to be enumerated - no guess at the folder name, and
// installdir comes out of Steam's own record of it.
static bool TrySteamLibrary(const wchar_t* lib, wchar_t* out, size_t n)
{
    wchar_t acf[MAX_PATH];
    Join(acf, _countof(acf), lib, L"steamapps\\appmanifest_" STEAM_APPID L".acf");
    if (!Exists(acf)) return false;

    wchar_t common[MAX_PATH];
    Join(common, _countof(common), lib, L"steamapps\\common");

    if (char* text = ReadAll(acf))
    {
        char value[MAX_PATH] = {0};
        if (const char* at = strstr(text, "\"installdir\""))
            VdfValue(at + 12, value, sizeof(value));
        free(text);

        if (value[0])
        {
            wchar_t leaf[MAX_PATH], dir[MAX_PATH];
            Widen(value, leaf, _countof(leaf));
            Join(dir, _countof(dir), common, leaf);
            if (IsGameDir(dir, out, n)) return true;
        }
    }

    // The manifest was there but installdir did not resolve - a renamed folder,
    // or a manifest for a move that never finished. Scan the library instead.
    return FindInChildren(common, out, n);
}

static bool RegString(HKEY root, const wchar_t* key, const wchar_t* value,
                      wchar_t* out, DWORD bytes)
{
    HKEY h;
    if (RegOpenKeyExW(root, key, 0, KEY_QUERY_VALUE, &h) != ERROR_SUCCESS) return false;

    // One character short, so a value stored without its terminator - which the
    // registry permits - still comes back as a string.
    DWORD type = 0, n = bytes - sizeof(wchar_t);
    out[0] = 0;
    LSTATUS rc = RegQueryValueExW(h, value, NULL, &type, (BYTE*)out, &n);
    RegCloseKey(h);

    if (rc != ERROR_SUCCESS || type != REG_SZ) return false;
    out[n / sizeof(wchar_t)] = 0;
    return out[0] != 0;
}

static bool FindViaSteam(wchar_t* out, size_t n)
{
    wchar_t steam[MAX_PATH] = {0};
    if (!RegString(HKEY_CURRENT_USER, L"Software\\Valve\\Steam", L"SteamPath",
                   steam, sizeof(steam)) &&
        !RegString(HKEY_LOCAL_MACHINE, L"SOFTWARE\\WOW6432Node\\Valve\\Steam",
                   L"InstallPath", steam, sizeof(steam)) &&
        !RegString(HKEY_LOCAL_MACHINE, L"SOFTWARE\\Valve\\Steam",
                   L"InstallPath", steam, sizeof(steam)))
        return false;

    // SteamPath is written with forward slashes and in lower case.
    for (wchar_t* p = steam; *p; p++) if (*p == L'/') *p = L'\\';
    Msg(L"steam at %s", steam);

    if (TrySteamLibrary(steam, out, n)) return true;

    wchar_t vdf[MAX_PATH];
    Join(vdf, _countof(vdf), steam, L"steamapps\\libraryfolders.vdf");
    char* text = ReadAll(vdf);
    if (!text) return false;

    bool found = false;
    const char* p = text;
    while (const char* at = strstr(p, "\"path\""))
    {
        char value[MAX_PATH] = {0};
        p = VdfValue(at + 6, value, sizeof(value));
        if (!p) break;
        if (!value[0]) continue;

        wchar_t lib[MAX_PATH];
        Widen(value, lib, _countof(lib));
        if (TrySteamLibrary(lib, out, n)) { found = true; break; }
    }

    free(text);
    return found;
}

// ---------------------------------------------------------------- the version gate
//
// Whole-file binary read, used by both halves below. ReadAll above is
// char-based and capped at 4 MB for Steam's vdf files; SOVIET64.exe is 10 MB
// and a plugin DLL can be larger still, and both of their paths are wide.
static unsigned char* ReadBinary(const wchar_t* path, size_t* outLen)
{
    HANDLE h = CreateFileW(path, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE,
                           NULL, OPEN_EXISTING, 0, NULL);
    if (h == INVALID_HANDLE_VALUE) return NULL;

    DWORD size = GetFileSize(h, NULL);
    if (size == INVALID_FILE_SIZE || size > (64u << 20)) { CloseHandle(h); return NULL; }

    unsigned char* buf = (unsigned char*)malloc(size ? size : 1);
    DWORD got = 0;
    if (!buf || !ReadFile(h, buf, size, &got, NULL)) { free(buf); CloseHandle(h); return NULL; }

    CloseHandle(h);
    *outLen = got;
    return buf;
}

// What the exe on disk turned out to be.
//
//   GV_OK          this is the build every address was verified against
//   GV_REBUILD     it says 1.1.1.7 and is not the same binary - a hotfix that
//                  left the printed version alone. Allowed, and said out loud
//   GV_WRONG       it says something else. Refused
//   GV_UNKNOWN     the numbers could not be read and the stamp does not match.
//                  Refused, because "not recognisable" is not "fine"
enum { GV_OK = 0, GV_REBUILD, GV_WRONG, GV_UNKNOWN };

struct GameVersion
{
    int      v[4];              // -1 when the numbers could not be read
    bool     known;
    unsigned stamp;             // PE TimeDateStamp, 0 when the headers would not parse
    int      verdict;
    wchar_t  text[32];          // "1.1.1.7", or "unknown"
};

// The one string the game formats its own version line from. It is the
// anchor for everything below: find it, find the instruction that points at
// it, and the four numbers are in the argument set-up right in front of that
// instruction.
static const char kVersionFormat[] = "v%d.%d.%d.%d (64 bit DX11.1)";

static const unsigned char* FindBytes(const unsigned char* hay, size_t hayLen,
                                      const void* needle, size_t needleLen)
{
    if (needleLen == 0 || hayLen < needleLen) return NULL;
    const unsigned char* first = (const unsigned char*)needle;
    for (size_t i = 0; i + needleLen <= hayLen; i++)
        if (hay[i] == *first && memcmp(hay + i, needle, needleLen) == 0)
            return hay + i;
    return NULL;
}

static unsigned Rd32(const unsigned char* p) { unsigned v; memcpy(&v, p, 4); return v; }

// Reads the version out of SOVIET64.exe without running it or loading it as a
// module - the file is parsed as data, which is the only safe way to look at an
// executable this program is about to inject into.
//
// The game has no VERSIONINFO resource, so the version has to come from the
// code. The main menu prints it through
//
//     sprintf(buf, "v%d.%d.%d.%d (64 bit DX11.1)", 1, 1, 1, 7)
//
// and in the 1.1.1.7 build that call site sets its arguments up like this, at
// rva 0x28C775..0x28C788:
//
//     C7 44 24 20 07 00 00 00    mov  dword ptr [rsp+0x20], 7   ; 5th arg
//     BA 01 00 00 00             mov  edx, 1                    ; 2nd
//     44 8B CA                   mov  r9d, edx                  ; 4th
//     44 8B C2                   mov  r8d, edx                  ; 3rd
//     48 8D 0D 51 9A 60 00       lea  rcx, [rip+0x609A51]       ; the format
//
// So: locate the format string in .rdata, scan .text for the one rip-relative
// lea that resolves to it, and read the four immediates out of the 64 bytes in
// front of it. The scan is deliberately not a disassembler - it looks for the
// exact encodings that can put a small constant in each of those four places,
// and the last write to each wins, which is the order a real decode would have
// produced anyway. Anything it does not recognise leaves the numbers unread
// rather than wrong, and the TimeDateStamp still has the final say.
static void ReadGameVersion(const wchar_t* exe, GameVersion* g)
{
    memset(g, 0, sizeof(*g));
    g->v[0] = g->v[1] = g->v[2] = g->v[3] = -1;
    g->verdict = GV_UNKNOWN;
    wcscpy_s(g->text, _countof(g->text), L"unknown");

    size_t len = 0;
    unsigned char* d = ReadBinary(exe, &len);
    if (!d) return;

    for (;;)                                    // one pass, `break` is the exit
    {
        if (len < 0x400 || d[0] != 'M' || d[1] != 'Z') break;

        // Every bound here is computed in size_t against `len`, never in the
        // 32-bit type the field is stored in. `pe + 0x108` in `unsigned` wraps
        // for a large e_lfanew, and a wrapped sum is smaller than len, so a
        // corrupt or hostile header used to pass this test and send the memcmp
        // below several gigabytes past the end of the buffer.
        size_t pe = (size_t)Rd32(d + 0x3C);
        if (pe > len || len - pe < 0x108) break;
        if (memcmp(d + pe, "PE\0\0", 4) != 0) break;

        unsigned short nsec  = *(unsigned short*)(d + pe + 6);
        unsigned short optsz = *(unsigned short*)(d + pe + 20);
        unsigned short magic = *(unsigned short*)(d + pe + 24);
        g->stamp = Rd32(d + pe + 8);

        if (magic != 0x20B) break;              // not PE32+, so not this game
        if (!nsec || nsec > 96) break;

        size_t secOff = pe + 24 + (size_t)optsz;
        if (secOff > len || (len - secOff) / 40 < (size_t)nsec) break;

        // The format string, and the rva it lives at.
        const unsigned char* at = FindBytes(d, len, kVersionFormat, sizeof(kVersionFormat));
        if (!at) break;
        size_t strFile = (size_t)(at - d);

        unsigned strRva = 0, textRva = 0, textOff = 0, textLen = 0;
        for (int i = 0; i < nsec; i++)
        {
            const unsigned char* s = d + secOff + i * 40;
            unsigned vaddr = Rd32(s + 12), rsize = Rd32(s + 16), raddr = Rd32(s + 20);
            if (raddr > len || rsize > len - raddr) continue;

            if (strFile >= raddr && strFile < (size_t)raddr + rsize)
                strRva = vaddr + (unsigned)(strFile - raddr);
            if (memcmp(s, ".text", 5) == 0 && !textRva)
            {
                textRva = vaddr;
                textOff = raddr;
                textLen = rsize;
            }
        }
        if (!strRva || !textLen) break;

        // lea r64, [rip+disp32]: 48/4C 8D, modrm mod=00 rm=101. The whole
        // instruction is 7 bytes and rip is what follows it.
        const unsigned char* text = d + textOff;
        const unsigned char* lea  = NULL;
        for (unsigned i = 0; i + 7 <= textLen; i++)
        {
            if ((text[i] != 0x48 && text[i] != 0x4C) || text[i + 1] != 0x8D) continue;
            if ((text[i + 2] & 0xC7) != 0x05) continue;

            int disp = (int)Rd32(text + i + 3);
            if (textRva + i + 7 + (unsigned)disp == strRva) { lea = text + i; break; }
        }
        if (!lea) break;

        // The 64 bytes in front of it. Each pattern is one way of putting a
        // small constant into one of the four argument slots; edx feeds r8d and
        // r9d in this build, which is why the version reads 1.1.1 from a single
        // immediate.
        const unsigned char* w = (lea - text >= 64) ? lea - 64 : text;
        int edx = -1, r8 = -1, r9 = -1, stk = -1;

        for (const unsigned char* p = w; p + 2 < lea; p++)
        {
            unsigned imm;
            if (p[0] == 0xBA && p + 5 <= lea && (imm = Rd32(p + 1)) < 256)
                edx = (int)imm;                                     // mov edx, imm32
            else if (p[0] == 0x41 && p[1] == 0xB8 && p + 6 <= lea && (imm = Rd32(p + 2)) < 256)
                r8 = (int)imm;                                      // mov r8d, imm32
            else if (p[0] == 0x41 && p[1] == 0xB9 && p + 6 <= lea && (imm = Rd32(p + 2)) < 256)
                r9 = (int)imm;                                      // mov r9d, imm32
            else if (p[0] == 0x44 && p[1] == 0x8B && p[2] == 0xC2)
                r8 = edx;                                           // mov r8d, edx
            else if (p[0] == 0x44 && p[1] == 0x8B && p[2] == 0xCA)
                r9 = edx;                                           // mov r9d, edx
            else if (p[0] == 0xC7 && p[1] == 0x44 && p[2] == 0x24 && p + 8 <= lea &&
                     (imm = Rd32(p + 4)) < 256)
                stk = (int)imm;                                     // mov [rsp+d8], imm32
        }

        if (edx < 0 || r8 < 0 || r9 < 0 || stk < 0) break;

        g->v[0] = edx; g->v[1] = r8; g->v[2] = r9; g->v[3] = stk;
        g->known = true;
        _snwprintf_s(g->text, _countof(g->text), _TRUNCATE, L"%d.%d.%d.%d",
                     g->v[0], g->v[1], g->v[2], g->v[3]);
        break;
    }

    free(d);

    // The verdict, checked against every entry in kSupportedVersions rather
    // than one pair. The stamp is the stronger fact and settles both of the
    // cases the numbers cannot: an exe whose numbers would not read is still a
    // supported build if it is byte-for-byte one the stamp names, and one that
    // reads e.g. 1.1.1.7 out of a different binary is a rebuild of that entry
    // rather than the build.
    int  byNumbers   = -1;      // index into kSupportedVersions matching g->v[], or -1
    bool stampKnown  = false;   // g->stamp equals some entry's stamp

    for (size_t i = 0; i < GAME_VER_COUNT; i++)
    {
        const SupportedGameVersion* sv = &kSupportedVersions[i];
        if (g->known && byNumbers < 0 &&
            g->v[0] == sv->v[0] && g->v[1] == sv->v[1] &&
            g->v[2] == sv->v[2] && g->v[3] == sv->v[3])
            byNumbers = (int)i;
        if (g->stamp == sv->stamp)
            stampKnown = true;
    }

    if (byNumbers >= 0)
        g->verdict = (g->stamp == kSupportedVersions[byNumbers].stamp) ? GV_OK : GV_REBUILD;
    else if (g->known)
        g->verdict = GV_WRONG;
    else
        g->verdict = stampKnown ? GV_OK : GV_UNKNOWN;
}

// One exe is asked about many times - at startup, when the path changes, and
// again on Launch - and reading 10 MB per keystroke is not free. Keyed on the
// path, so a different path is always re-read.
static wchar_t     g_verPath[MAX_PATH];
static GameVersion g_ver;

static const GameVersion* GameVersionOf(const wchar_t* exe)
{
    if (!exe || !exe[0]) return NULL;

    if (_wcsicmp(g_verPath, exe) != 0)
    {
        ReadGameVersion(exe, &g_ver);
        wcscpy_s(g_verPath, _countof(g_verPath), exe);

        Msg(L"game version %s (build %08X), %s", g_ver.text, g_ver.stamp,
            g_ver.verdict == GV_OK      ? L"supported" :
            g_ver.verdict == GV_REBUILD ? L"supported version, different build" :
            g_ver.verdict == GV_WRONG   ? L"NOT supported" : L"unreadable");
    }
    return &g_ver;
}

// Whether this exe may be injected into. The switch is deliberately not in the
// window: turning the gate off is for whoever is porting the addresses to a new
// build, and that person can edit an ini or pass a flag.
static bool g_versionCheck = true;

static bool VersionRefuses(const GameVersion* g)
{
    if (!g_versionCheck) return false;
    return !g || g->verdict == GV_WRONG || g->verdict == GV_UNKNOWN;
}

// The two lines the window shows, and what --find prints. `req` never changes -
// it is the whole point that the supported version is stated even when nothing
// is wrong - and `got` is what this exe turned out to be.
static void VersionRequirementText(wchar_t* out, size_t n)
{
    _snwprintf_s(out, n, _TRUNCATE,
                 g_versionCheck
                     ? L"Requires Workers & Resources %s (64 bit)"
                     : L"Built for Workers & Resources %s (64 bit) - the check "
                       L"is off, other versions may crash.",
                 SupportedVersionsText());
}

static void VersionStatusText(const GameVersion* g, wchar_t* out, size_t n)
{
    if (!g) { wcscpy_s(out, n, L"Installed: no game selected"); return; }

    switch (g->verdict)
    {
    case GV_OK:
        _snwprintf_s(out, n, _TRUNCATE, L"Installed: v%s - supported", g->text);
        break;
    case GV_REBUILD:
        _snwprintf_s(out, n, _TRUNCATE,
                     L"Installed: v%s, but a different build of it (%08X) - "
                     L"patches may not fit", g->text, g->stamp);
        break;
    case GV_WRONG:
        _snwprintf_s(out, n, _TRUNCATE,
                     L"Installed: v%s - NOT supported, %s", g->text,
                     g_versionCheck ? L"launch refused" : L"launching anyway");
        break;
    default:
        _snwprintf_s(out, n, _TRUNCATE,
                     L"Installed: version could not be read - %s",
                     g_versionCheck ? L"launch refused" : L"launching anyway");
        break;
    }
}

// ---------------------------------------------------------------- config
//
// The ini beside the DLL, which is the one the loader reads: baseDir there is
// the folder tesmioloader.dll lives in, not this program's folder, and --dll can
// make those different.
//
// The plugin keys go through the ANSI profile API because that is what the
// loader uses, so both sides agree on what a key looks like. game_exe goes
// through the wide one - it is a path, this program is its only reader, and a
// non-ASCII folder name is at least worth trying to keep.

static wchar_t g_ini[MAX_PATH];
static char    g_iniA[MAX_PATH];
static wchar_t g_version[64] = L"";

struct PluginEntry
{
    wchar_t  file[64];      // resources.dll
    char     key[64];       // resources - the [plugins] key, and the loader's
    bool     on;
    HWND     box;
    unsigned apiVersion;    // what TsmPluginApiVersion() returned, 0 if unreadable
    bool     apiKnown;      // the export was found and called without faulting
    bool     apiOk;         // apiKnown && apiVersion == TSM_API_VERSION
    int      sig;           // TSM_SIG_* - whose signature the DLL carries
};

// The three answers the signature check can give. NONE and BAD both mean "not
// from Tesmio"; BAD is the stronger statement - a signature file exists and
// does not verify, so the bytes changed after somebody signed them.
#define TSM_SIG_NONE 0      // no <name>.dll.sig beside the DLL
#define TSM_SIG_OK   1      // the signature verifies against TSM_PUBLIC_KEY
#define TSM_SIG_BAD  2      // a .sig is there and does not verify
static PluginEntry g_plug[MAX_PLUGINS];
static int         g_plugCount;
static bool        g_host = true;       // [tesmioloader] plugins

// Both spellings of the one path. The plugin keys go through the ANSI profile
// API because that is what the loader uses, so both sides agree on what a key
// looks like; game_exe goes through the wide one.
//
// THAT ONLY WORKS WHILE THE PATH ROUND-TRIPS THROUGH THE SYSTEM CODEPAGE. On an
// install under, say, D:\Игры\ on a non-Cyrillic system, WideCharToMultiByte
// substitutes '?' for what it cannot encode, and the ANSI path then names a
// file that does not exist - so every [plugins] read silently returns its
// default and every write silently goes nowhere. That used to happen with no
// symptom at all beyond checkboxes that would not stick.
//
// It cannot be fixed here (the loader reads the same file through the same ANSI
// API, so switching this side alone would only move the disagreement), but it
// can be detected and said out loud.
static void SetIniPath(const wchar_t* dllDir)
{
    Join(g_ini, _countof(g_ini), dllDir, LOADER_INI);

    BOOL lossy = FALSE;
    int n = WideCharToMultiByte(CP_ACP, 0, g_ini, -1, g_iniA, sizeof(g_iniA),
                                NULL, &lossy);
    if (n == 0)
    {
        g_iniA[0] = 0;
        Msg(L"WARNING: %s cannot be expressed in the system codepage at all - "
            L"plugin on/off settings will not be saved or read.", g_ini);
    }
    else if (lossy)
    {
        Msg(L"WARNING: %s contains characters outside the system codepage. "
            L"tesmioloader reads this file through the ANSI profile API, so the "
            L"plugin on/off settings will not stick. Install to a path made of "
            L"plain ASCII.", g_ini);
    }
}

// Loads a plugin DLL just far enough to ask it TsmPluginApiVersion(), then
// unloads it again - the same two GetProcAddress calls and the same SEH guard
// tesmioloader.cpp's LoadPlugins uses before it will call Init, just run here
// so a mismatch is visible in the launcher window rather than only in
// tesmioloader.log after the game has already been injected.
//
// Every shipped plugin's DllMain is a bare `return TRUE` on attach - the real
// work happens in TsmPluginInit, which this never calls - so loading it here,
// in the launcher's own process, does nothing the plugin would not have done
// harmlessly anyway. FreeLibrary's DLL_PROCESS_DETACH is likewise a no-op: the
// one plugin that closes a handle there (resources.dll) guards it with the
// INVALID_HANDLE_VALUE its static keeps until Init runs, which never happens.
//
// Returns false when the DLL would not load at all or carries no
// TsmPluginApiVersion export - "not a tesmioloader plugin", the loader's own
// other rejection reason - rather than a version number.
static bool QueryPluginApiVersion(const wchar_t* fullPath, unsigned* out)
{
    *out = 0;

    HMODULE mod = LoadLibraryExW(fullPath, NULL, LOAD_WITH_ALTERED_SEARCH_PATH);
    if (!mod) return false;

    TsmPluginApiVersionFn ver =
        (TsmPluginApiVersionFn)GetProcAddress(mod, TSM_EXPORT_APIVERSION);
    if (!ver) { FreeLibrary(mod); return false; }

    unsigned got = 0;
    bool ok = true;
    __try { got = ver(); }
    __except (EXCEPTION_EXECUTE_HANDLER) { ok = false; }

    FreeLibrary(mod);
    if (!ok) return false;

    *out = got;
    return true;
}

// Verifies <dllPath>.sig against the bytes of dllPath, using the public key
// this binary was built with. The signature covers the DLL exactly as it sits
// on disk, so editing the file - one byte is enough - turns a valid seal into
// TSM_SIG_BAD, while deleting the .sig turns it into the honest TSM_SIG_NONE.
#if TSM_LAUNCHER_SIGNING
static int CheckPluginSignature(const wchar_t* dllPath)
{
    // A public blob with the wrong magic means this launcher was built without
    // a generated tesmio_pubkey.h, in which case there is nobody to verify
    // against and every plugin reports NONE rather than BAD.
    DWORD magic = 0, cbKey = 0;
    memcpy(&magic, TSM_PUBLIC_KEY, 4);
    memcpy(&cbKey, TSM_PUBLIC_KEY + 4, 4);
    if (magic != BCRYPT_ECDSA_PUBLIC_P256_MAGIC || cbKey != 32)
        return TSM_SIG_NONE;

    wchar_t sigPath[MAX_PATH];
    _snwprintf_s(sigPath, _countof(sigPath), _TRUNCATE, L"%s.sig", dllPath);
    if (!Exists(sigPath)) return TSM_SIG_NONE;

    int result = TSM_SIG_BAD;

    size_t sigFileLen = 0;
    unsigned char* sigFile = ReadBinary(sigPath, &sigFileLen);
    if (sigFile && sigFileLen > sizeof(TsmSigHeader))
    {
        TsmSigHeader* hdr = (TsmSigHeader*)sigFile;
        size_t body = sigFileLen - sizeof(TsmSigHeader);

        if (memcmp(hdr->magic, TSM_SIG_MAGIC, TSM_SIG_MAGIC_LEN) == 0 &&
            hdr->version == 1 && hdr->sigLen == body)
        {
            size_t dllLen = 0;
            unsigned char* dll = ReadBinary(dllPath, &dllLen);
            if (dll)
            {
                if (TsmVerifySignature(dll, dllLen,
                                       sigFile + sizeof(TsmSigHeader), body,
                                       TSM_PUBLIC_KEY, TSM_ECC_PUBLIC_BLOB_SIZE))
                    result = TSM_SIG_OK;
                free(dll);
            }
        }
    }

    free(sigFile);
    return result;
}
#else
// No signing headers at build time: nothing can be verified, and NONE is the
// one answer that never lies - PluginSigNote below turns it into silence
// rather than into "not from Tesmio".
static int CheckPluginSignature(const wchar_t*) { return TSM_SIG_NONE; }
#endif

// Empty when the plugin's own reported version is one this loader accepts.
// Otherwise the same two rejection reasons LoadPlugins logs - "not initialised"
// or "no TsmPluginApiVersion export" - phrased for the window and the --find
// printout rather than the log file.
//
// `brief` is the window's form. A checkbox in a two-column list has room for
// roughly fifty characters, and the long form is written for a console line
// that has as many as it likes.
static void PluginWarning(const PluginEntry* e, wchar_t* out, size_t n, bool brief)
{
    out[0] = 0;
    if (e->apiOk) return;

    // A file whose signature does not verify was deliberately not loaded, so
    // there is no API version to report and "not a tesmioloader plugin" would
    // be a claim nothing checked. The signature note already says everything.
    if (e->sig == TSM_SIG_BAD)
    {
        wcscpy_s(out, n, brief ? L"not loaded" : L"not loaded - signature does not verify");
        return;
    }

    // One sentence for both directions. A plugin can be too old (built before
    // TSM_API_VERSION_MIN, so a field it reads has moved) or too new (built
    // against a header this loader does not have yet), and the range says which
    // without the reader having to be told the rule.
    if (e->apiKnown)
        _snwprintf_s(out, n, _TRUNCATE,
                     brief ? L"API %u, needs %u-%u"
                           : L"incompatible: reports API %u, this loader takes %u to %u",
                     e->apiVersion, TSM_API_VERSION_MIN, TSM_API_VERSION);
    else
        wcscpy_s(out, n, brief ? L"not a plugin" : L"not a tesmioloader plugin");
}

// The provenance half of a plugin's label, and only a valid seal is stated.
//
// A plugin with no .sig gets NOTHING - no mark at all. It used to say "not from
// Tesmio", which reads as an accusation against every third-party plugin and
// against every build made from source without the private key, which is most
// of them. Absence of a mark is the honest form of "nobody claims to have built
// this", and the mark that is there means what it says.
//
// A signature that exists and does not verify is the one case that still
// speaks. It is not "unsigned": somebody signed these bytes and the bytes then
// changed, and silence there would read as ordinary third-party provenance.
static void PluginSigNote(const PluginEntry* e, wchar_t* out, size_t n, bool brief)
{
    out[0] = 0;
#if TSM_LAUNCHER_SIGNING
    switch (e->sig)
    {
    case TSM_SIG_OK:  wcscpy_s(out, n, brief ? L"tesmio" : L"signed by Tesmio"); break;
    case TSM_SIG_BAD: wcscpy_s(out, n, L"SIGNATURE INVALID"); break;
    default:          break;                    // unsigned: say nothing
    }
#else
    (void)e; (void)n; (void)brief;
#endif
}

// Everything the window and --find have to say about a plugin, in one string:
// whose signature it carries, then whether this loader will initialise it.
// Can come back empty, and both callers then print the bare file name.
static void PluginNote(const PluginEntry* e, wchar_t* out, size_t n, bool brief)
{
    wchar_t sig[96], warn[96];
    PluginSigNote(e, sig, _countof(sig), brief);
    PluginWarning(e, warn, _countof(warn), brief);

    if (sig[0] && warn[0])
        _snwprintf_s(out, n, _TRUNCATE, L"%s, %s", sig, warn);
    else if (warn[0])
        wcscpy_s(out, n, warn);
    else
        wcscpy_s(out, n, sig);
}

// Alphabetical, which is what FindFirstFile gives on NTFS and the order the
// loader will load them in.
static void ScanPlugins(const wchar_t* dllDir)
{
    wchar_t pluginsDir[MAX_PATH];
    Join(pluginsDir, _countof(pluginsDir), dllDir, L"plugins");

    wchar_t pattern[MAX_PATH];
    Join(pattern, _countof(pattern), pluginsDir, L"*.dll");

    WIN32_FIND_DATAW fd;
    HANDLE h = FindFirstFileW(pattern, &fd);
    if (h == INVALID_HANDLE_VALUE) return;

    do
    {
        if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) continue;
        if (g_plugCount >= MAX_PLUGINS) break;

        PluginEntry* e = &g_plug[g_plugCount++];
        memset(e, 0, sizeof(*e));
        wcscpy_s(e->file, _countof(e->file), fd.cFileName);

        wchar_t stem[64];
        wcscpy_s(stem, _countof(stem), fd.cFileName);
        if (wchar_t* dot = wcsrchr(stem, L'.')) *dot = 0;
        WideCharToMultiByte(CP_ACP, 0, stem, -1, e->key, sizeof(e->key), NULL, NULL);

        e->on = GetPrivateProfileIntA("plugins", e->key, 1, g_iniA) != 0;

        wchar_t full[MAX_PATH];
        Join(full, _countof(full), pluginsDir, fd.cFileName);

        // THE SIGNATURE IS CHECKED FIRST, and the order is the whole point.
        //
        // QueryPluginApiVersion below calls LoadLibraryExW, which runs the
        // DLL's DllMain in THIS process. Doing that before deciding anything
        // about the file made the signature mark decorative: by the time a
        // tampered plugin was labelled SIGNATURE INVALID, its code had already
        // executed in the launcher. Reading the bytes and verifying them
        // touches no code at all, so it is what goes first.
        e->sig = CheckPluginSignature(full);

        // The same range LoadPlugins accepts, and it must stay the same range:
        // a box the launcher ticks and the loader then refuses would be lying
        // about what ticking it does. See tesmio_api.h on TSM_API_VERSION_MIN.
        //
        // A file carrying a signature that does NOT verify is never loaded.
        // Somebody signed those bytes and the bytes then changed, which is the
        // one case where refusing to execute it costs nothing: the launcher
        // still lists it, still marks it red, and the loader still makes its
        // own decision - this only declines to run it here, to find out a
        // version number the window would print in brackets.
        if (e->sig == TSM_SIG_BAD)
        {
            e->apiKnown = false;
            e->apiVersion = 0;
        }
        else
        {
            e->apiKnown = QueryPluginApiVersion(full, &e->apiVersion);
        }
        e->apiOk    = e->apiKnown &&
                      e->apiVersion >= TSM_API_VERSION_MIN &&
                      e->apiVersion <= TSM_API_VERSION;

        // The loader will refuse to initialise this one regardless of what the
        // ini says, so a checked box would be lying about what ticking it
        // does. Forcing it off here is what SaveConfig then persists, and what
        // the checkbox below is built already unchecked from.
        if (!e->apiOk) e->on = false;
    } while (FindNextFileW(h, &fd));

    FindClose(h);
}

static void ReadConfig()
{
    g_host = GetPrivateProfileIntA("tesmioloader", "plugins", 1, g_iniA) != 0;
    GetPrivateProfileStringW(L"tesmioloader", L"version", L"unknown",
                             g_version, _countof(g_version), g_ini);

    // The version gate. Absent means on: a fresh install must refuse a game it
    // cannot patch, and turning that off has to be something someone did on
    // purpose. --ignore-version does the same for one run.
    g_versionCheck = GetPrivateProfileIntA("tesmioloader", "version_check", 1, g_iniA) != 0;
}

// Creates the ini when it is not there. Everything the loader does not find in
// it falls back to the same compiled default it would have used with no file at
// all, so a file holding only these keys behaves as before - and the game path
// is remembered even on an install that arrived without an ini.
//
// The profile API never writes a BOM and edits in place, so the comments in the
// shipped file survive. That matters: writing this file with PowerShell's
// -Encoding UTF8 has broken the whole config once already.
static void SaveConfig(const wchar_t* gameExe)
{
    WritePrivateProfileStringW(L"tesmioloader", L"game_exe", gameExe, g_ini);
    WritePrivateProfileStringA("tesmioloader", "plugins", g_host ? "1" : "0", g_iniA);

    // Not a setting - regenerated from `version` on every launch and written
    // straight into the loader's own [tesmioloader] section, so nobody has to
    // keep the two in step by hand. (This used to land under "tsmloader" -
    // one letter short of the section tesmioloader.cpp's ReadConfig actually
    // reads - which is why the menu kept showing its compiled-in default no
    // matter what `version` said.)
    char versionA[64] = {0};
    WideCharToMultiByte(CP_ACP, 0, g_version, -1, versionA, sizeof(versionA), NULL, NULL);
    char menu_tagA[128];
    _snprintf_s(menu_tagA, _countof(menu_tagA), _TRUNCATE, "tesmioloader v. %s", versionA);
    WritePrivateProfileStringA("tesmioloader", "menu_tag", menu_tagA, g_iniA);

    for (int i = 0; i < g_plugCount; i++)
        WritePrivateProfileStringA("plugins", g_plug[i].key,
                                   g_plug[i].on ? "1" : "0", g_iniA);
}

// ---------------------------------------------------------------- injection

static bool Inject(const wchar_t* gameFull, const wchar_t* dllFull)
{
    wchar_t workDir[MAX_PATH];
    wcscpy_s(workDir, _countof(workDir), gameFull);
    ToParent(workDir);

    Msg(L"game %s", gameFull);
    Msg(L"dll  %s", dllFull);
    Msg(L"cwd  %s", workDir);

    wchar_t cmdline[MAX_PATH + 4];
    _snwprintf_s(cmdline, _countof(cmdline), _TRUNCATE, L"\"%s\"", gameFull);

    STARTUPINFOW si = { sizeof(si) };
    PROCESS_INFORMATION pi = {0};

    if (!CreateProcessW(gameFull, cmdline, NULL, NULL, FALSE,
                        CREATE_SUSPENDED, NULL, workDir, &si, &pi))
    {
        Fail(L"CreateProcess");
        return false;
    }
    Msg(L"pid %lu created suspended", pi.dwProcessId);

    bool ok = false;
    bool threadStarted = false;
    SIZE_T bytes = (wcslen(dllFull) + 1) * sizeof(wchar_t);
    LPVOID remote = VirtualAllocEx(pi.hProcess, NULL, bytes,
                                   MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);

    if (!remote)
        Fail(L"VirtualAllocEx");
    else if (!WriteProcessMemory(pi.hProcess, remote, dllFull, bytes, NULL))
        Fail(L"WriteProcessMemory");
    else
    {
        // kernel32 sits at the same base in every process of a boot session,
        // so our own LoadLibraryW address is valid in the target.
        FARPROC loadLib = GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "LoadLibraryW");
        if (!loadLib)
            Fail(L"GetProcAddress(LoadLibraryW)");
        else
        {
            HANDLE th = CreateRemoteThread(pi.hProcess, NULL, 0,
                                           (LPTHREAD_START_ROUTINE)loadLib, remote, 0, NULL);
            if (!th)
                Fail(L"CreateRemoteThread");
            else
            {
                threadStarted = true;

                // The wait result has to be checked, not just the exit code.
                // On a timeout GetExitCodeThread hands back STILL_ACTIVE (259),
                // which is non-zero and used to read as "the DLL loaded" - so
                // the game was resumed and, worse, the remote path buffer was
                // freed below while LoadLibraryW was very likely still reading
                // it. A timeout is a failure, and the process is torn down.
                DWORD waited = WaitForSingleObject(th, 30000);
                DWORD loaded = 0;

                if (waited != WAIT_OBJECT_0)
                {
                    Msg(L"LoadLibraryW did not finish within 30 s (%s) - "
                        L"the game will not be started",
                        waited == WAIT_TIMEOUT ? L"timed out" : L"wait failed");
                }
                else if (!GetExitCodeThread(th, &loaded))
                {
                    Fail(L"GetExitCodeThread");
                }
                else if (!loaded)
                {
                    Msg(L"LoadLibraryW returned NULL - the DLL did not load");
                }
                else if (ResumeThread(pi.hThread) == (DWORD)-1)
                {
                    Fail(L"ResumeThread");
                }
                else
                {
                    Msg(L"tesmioloader.dll loaded, game resumed");
                    ok = true;
                }
                CloseHandle(th);

                // Only safe to hand the page back once the remote thread has
                // actually finished with it.
                if (waited == WAIT_OBJECT_0)
                {
                    VirtualFreeEx(pi.hProcess, remote, 0, MEM_RELEASE);
                    remote = NULL;
                }
            }
        }
    }

    // `remote` is cleared above the moment the remote thread is known to have
    // finished with it. Anything still set here either never had a thread
    // pointed at it, or had one that did not come back - and in the second case
    // freeing the page under a thread that may still be reading it is exactly
    // the bug being fixed. TerminateProcess reclaims the whole address space, so
    // the page is only handed back when no thread was ever started.
    if (remote && !threadStarted) VirtualFreeEx(pi.hProcess, remote, 0, MEM_RELEASE);
    if (!ok) TerminateProcess(pi.hProcess, 1);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return ok;
}

// ---------------------------------------------------------------- the window
//
// Plain Win32, controls created by hand. Metrics are written at 96 dpi and
// scaled through S(), and the process declares itself dpi-aware, so the window
// is crisp on a scaled display rather than bitmap-stretched.

#define IDC_LAUNCH  IDOK            // so IsDialogMessage's Enter lands here
#define IDC_CLOSE   IDCANCEL        // and Escape here
#define IDC_PATH    100
#define IDC_BROWSE  101
#define IDC_HOST    102
#define IDC_STATUS  103
#define IDC_VERREQ  104             // "requires v1.1.1.7 or v1.1.1.9", always the same words
#define IDC_VERGOT  105             // what the exe on disk turned out to be
#define IDC_LIST    106             // the scrolling viewport the checkboxes live in
#define IDC_PLUGIN0 200

#define LIST_CLASS  L"tesmiopluginlist"
#define LIST_ROW    20              // one plugin row, 96 dpi
#define LIST_COLS   2
#define LIST_MAXROW 8               // taller than this and it scrolls instead

static HFONT   g_font;
static HWND    g_path;
static HWND    g_hostBox;
static HWND    g_verGot;
static HWND    g_list;
static int     g_dpi = 96;
static bool    g_launched;
static wchar_t g_dllFull[MAX_PATH];

static int S(int v) { return MulDiv(v, g_dpi, 96); }

// Physical pixels, all three - the list is scrolled and measured in device
// units, because a scroll position rounded through S() would drift.
static int g_listContent;           // the whole column of rows
static int g_listView;              // what fits on screen at once
static int g_listPos;               // how far down we are

static HWND ChildPx(HWND parent, const wchar_t* cls, const wchar_t* text,
                    DWORD style, int x, int y, int w, int h, int id)
{
    HWND c = CreateWindowExW(0, cls, text, WS_CHILD | WS_VISIBLE | style,
                             x, y, w, h, parent, (HMENU)(INT_PTR)id, NULL, NULL);
    if (c && g_font) SendMessageW(c, WM_SETFONT, (WPARAM)g_font, TRUE);
    return c;
}

static HWND Child(HWND parent, const wchar_t* cls, const wchar_t* text,
                  DWORD style, int x, int y, int w, int h, int id)
{
    return ChildPx(parent, cls, text, style, S(x), S(y), S(w), S(h), id);
}

// --- the plugin list -----------------------------------------------------
//
// A child window of its own rather than checkboxes on the dialog face, for one
// reason: the loader takes up to 32 plugins, and 32 rows at 20 px is taller
// than the work area of a 768-line laptop screen once everything else is on the
// window too. The old layout grew the window to fit the count, which at eight
// or so plugins put Launch off the bottom edge - visible only to whoever had
// that many installed.
//
// Two columns halve the rows, and WS_VSCROLL takes whatever is left over. The
// scroll is ScrollWindowEx with SW_SCROLLCHILDREN, so the checkboxes are moved
// by the OS and nothing has to be re-created or re-positioned by hand.
//
// A child window costs two things and both are paid below: its children's
// WM_COMMAND and WM_CTLCOLORSTATIC arrive here instead of at the main window
// and are forwarded, and tab traversal only descends into it because it is
// created WS_EX_CONTROLPARENT.

static void ListSetScroll(HWND list)
{
    SCROLLINFO si = { sizeof(si) };
    si.fMask = SIF_RANGE | SIF_PAGE | SIF_POS;
    si.nMin  = 0;
    si.nMax  = g_listContent > 0 ? g_listContent - 1 : 0;
    si.nPage = (UINT)(g_listView > 0 ? g_listView : 1);
    si.nPos  = g_listPos;

    // Without SIF_DISABLENOSCROLL Windows hides the bar outright when the range
    // fits the page, which is what should happen with six plugins in a list
    // that holds sixteen.
    SetScrollInfo(list, SB_VERT, &si, TRUE);
}

static void ListScrollTo(HWND list, int pos)
{
    int limit = g_listContent - g_listView;
    if (limit < 0) limit = 0;
    if (pos < 0)     pos = 0;
    if (pos > limit) pos = limit;
    if (pos == g_listPos) return;

    int dy = g_listPos - pos;
    g_listPos = pos;

    ScrollWindowEx(list, 0, dy, NULL, NULL, NULL, NULL,
                   SW_SCROLLCHILDREN | SW_INVALIDATE | SW_ERASE);
    ListSetScroll(list);
    UpdateWindow(list);
}

// Tab traversal can put the focus on a row that is scrolled out of sight, and a
// focus ring nobody can see is worse than no focus at all. A child's client y is
// already the scrolled one, so its position in the content is that plus g_listPos.
static void ListReveal(HWND list, HWND child)
{
    if (!child || GetParent(child) != list) return;

    RECT r;
    GetWindowRect(child, &r);

    POINT p = { r.left, r.top };
    ScreenToClient(list, &p);
    int h = r.bottom - r.top;

    if (p.y < 0)                     ListScrollTo(list, g_listPos + p.y);
    else if (p.y + h > g_listView)   ListScrollTo(list, g_listPos + (p.y + h - g_listView));
}

static LRESULT CALLBACK ListProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg)
    {
    case WM_VSCROLL:
    {
        SCROLLINFO si = { sizeof(si) };
        si.fMask = SIF_ALL;
        GetScrollInfo(hwnd, SB_VERT, &si);

        int pos = si.nPos;
        switch (LOWORD(wp))
        {
        case SB_LINEUP:        pos -= S(LIST_ROW);   break;
        case SB_LINEDOWN:      pos += S(LIST_ROW);   break;
        case SB_PAGEUP:        pos -= g_listView;    break;
        case SB_PAGEDOWN:      pos += g_listView;    break;
        case SB_TOP:           pos  = 0;             break;
        case SB_BOTTOM:        pos  = g_listContent; break;
        case SB_THUMBTRACK:
        case SB_THUMBPOSITION: pos  = si.nTrackPos;  break;
        default: return 0;
        }
        ListScrollTo(hwnd, pos);
        return 0;
    }

    case WM_MOUSEWHEEL:
    {
        UINT lines = 3;
        SystemParametersInfoW(SPI_GETWHEELSCROLLLINES, 0, &lines, 0);
        if (lines == 0 || lines > 20) lines = 3;    // 0 is "no scroll", WHEEL_PAGESCROLL is huge

        int delta = GET_WHEEL_DELTA_WPARAM(wp);
        ListScrollTo(hwnd, g_listPos - delta * (int)lines * S(LIST_ROW) / WHEEL_DELTA);
        return 0;
    }

    case WM_COMMAND:
        // A checkbox click, and BN_SETFOCUS from tab traversal. Both belong to
        // the main window; the second one also has to bring the row into view
        // first, because the focus may have landed below the fold.
        if (HIWORD(wp) == BN_SETFOCUS) ListReveal(hwnd, (HWND)lp);
        return SendMessageW(GetParent(hwnd), msg, wp, lp);

    case WM_CTLCOLORSTATIC:
        // Checkboxes ask their own parent, which is now this window rather than
        // the dialog - forwarded so the red-text rule stays in one place.
        return SendMessageW(GetParent(hwnd), msg, wp, lp);
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

static void SyncPluginBoxes()
{
    // An API mismatch keeps a box disabled even with "Load plugins at all"
    // checked - there is nothing a click could turn on, since LoadPlugins
    // rejects it before Init regardless of the ini.
    for (int i = 0; i < g_plugCount; i++)
        EnableWindow(g_plug[i].box, (g_host && g_plug[i].apiOk) ? TRUE : FALSE);
}

static void Browse(HWND owner)
{
    wchar_t file[MAX_PATH] = {0};
    GetWindowTextW(g_path, file, _countof(file));

    OPENFILENAMEW ofn = { sizeof(ofn) };
    ofn.hwndOwner   = owner;
    ofn.lpstrFilter = L"SOVIET64.exe\0SOVIET64.exe\0Executables\0*.exe\0";
    ofn.lpstrFile   = file;
    ofn.nMaxFile    = _countof(file);
    ofn.lpstrTitle  = L"Where is SOVIET64.exe?";
    ofn.Flags       = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;

    if (GetOpenFileNameW(&ofn)) SetWindowTextW(g_path, file);
}

// What the edit box currently names, resolved. A folder is accepted and the exe
// appended, because pasting the game folder is the obvious mistake to forgive.
static bool ResolveEdit(wchar_t* out, size_t n)
{
    wchar_t typed[MAX_PATH] = {0};
    GetWindowTextW(g_path, typed, _countof(typed));

    wchar_t* p = typed;
    while (*p == L' ' || *p == L'"') p++;
    for (wchar_t* e = p + wcslen(p); e > p && (e[-1] == L' ' || e[-1] == L'"'); ) *--e = 0;
    if (!*p) return false;

    if (DirExists(p)) return IsGameDir(p, out, n);

    if (!Exists(p)) return false;
    wcscpy_s(out, n, p);
    return true;
}

// --- the version line ----------------------------------------------------

static bool g_verRed;               // the detected-version line is not "supported"

static void SetVersionLine(const GameVersion* g)
{
    wchar_t line[192];
    VersionStatusText(g, line, _countof(line));

    g_verRed = g && g->verdict != GV_OK;
    if (g_verGot)
    {
        SetWindowTextW(g_verGot, line);
        InvalidateRect(g_verGot, NULL, TRUE);   // the colour may have changed too
    }
}

// Re-reads whatever exe the edit box currently names and re-labels the line.
// Called whenever that text can have changed - at startup, after Browse, when
// the box loses the focus - so the window is never stale. Launch asks again
// regardless, because that is the one that decides.
static const GameVersion* RefreshVersionUi()
{
    wchar_t game[MAX_PATH];
    const GameVersion* g = ResolveEdit(game, _countof(game)) ? GameVersionOf(game) : NULL;
    SetVersionLine(g);
    return g;
}

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg)
    {
    case WM_CTLCOLORSTATIC:
    {
        // Statics, group boxes and checkboxes all ask, and all of them sit on
        // the dialog face rather than on a white field.
        SetBkColor((HDC)wp, GetSysColor(COLOR_BTNFACE));

        HWND ctl = (HWND)lp;

        // The game version, when it is anything but the one this build patches.
        // Red because it is the difference between the game starting and the
        // game dying on the first hook.
        if (ctl == g_verGot && g_verRed)
        {
            SetTextColor((HDC)wp, RGB(176, 0, 0));
            return (LRESULT)GetSysColorBrush(COLOR_BTNFACE);
        }

        // A plugin box whose own reported API version this loader does not
        // accept is painted red rather than only carrying a bracketed suffix
        // in its label - the loader will refuse to initialise it exactly as
        // if it were unchecked, so the box lies about what ticking it does
        // unless the mismatch is obvious at a glance. A signature file that
        // does not verify gets the same red: the bytes changed after they
        // were signed, which is a stronger statement than "not from Tesmio".
        for (int i = 0; i < g_plugCount; i++)
        {
            if (g_plug[i].box == ctl &&
                (!g_plug[i].apiOk || g_plug[i].sig == TSM_SIG_BAD))
            {
                SetTextColor((HDC)wp, RGB(176, 0, 0));
                break;
            }
        }
        return (LRESULT)GetSysColorBrush(COLOR_BTNFACE);
    }

    case WM_MOUSEWHEEL:
        // The wheel goes to whatever has the focus, which is hardly ever the
        // list. Nothing else in this window scrolls, so hand it over.
        if (g_list) return SendMessageW(g_list, msg, wp, lp);
        return 0;

    case WM_COMMAND:
    {
        int id = LOWORD(wp);

        if (id == IDC_BROWSE) { Browse(hwnd); RefreshVersionUi(); return 0; }

        // Typing a path re-checks it when the box is left, not per keystroke:
        // the check reads the whole 10 MB exe.
        if (id == IDC_PATH && HIWORD(wp) == EN_KILLFOCUS) { RefreshVersionUi(); return 0; }

        if (id == IDC_HOST)
        {
            g_host = SendMessageW(g_hostBox, BM_GETCHECK, 0, 0) == BST_CHECKED;
            SyncPluginBoxes();
            return 0;
        }

        if (id >= IDC_PLUGIN0 && id < IDC_PLUGIN0 + g_plugCount)
        {
            PluginEntry* e = &g_plug[id - IDC_PLUGIN0];
            e->on = SendMessageW(e->box, BM_GETCHECK, 0, 0) == BST_CHECKED;
            return 0;
        }

        if (id == IDC_CLOSE) { DestroyWindow(hwnd); return 0; }

        if (id == IDC_LAUNCH)
        {
            wchar_t game[MAX_PATH];
            if (!ResolveEdit(game, _countof(game)))
            {
                MessageBoxW(hwnd,
                            L"That is not a Workers & Resources install.\n\n"
                            L"Point this at SOVIET64.exe, or at the folder holding it.",
                            L"tesmioloader", MB_ICONWARNING | MB_OK);
                SetFocus(g_path);
                return 0;
            }

            // The gate. Asked here rather than only at startup because the path
            // can have been edited since, and refused before anything is
            // written or started - a wrong game is not remembered as the one to
            // use next time either.
            const GameVersion* gv = GameVersionOf(game);
            SetVersionLine(gv);

            if (VersionRefuses(gv))
            {
                wchar_t what[64];
                if (gv && gv->known)
                    _snwprintf_s(what, _countof(what), _TRUNCATE, L"v%s", gv->text);
                else
                    wcscpy_s(what, _countof(what), L"a version that could not be read");

                // Not `msg`: that is WndProc's own UINT parameter, and shadowing
                // it here is a C4457 and an easy way to write the wrong one.
                wchar_t text[768];
                _snwprintf_s(text, _countof(text), _TRUNCATE,
                    L"This game is %s, and tesmioloader is built for %s.\n\n"
                    L"Every address it patches belongs to one of those builds. On "
                    L"any other, the hooks either refuse - leaving a loader that "
                    L"does nothing - or land in code that has moved, which crashes "
                    L"the game with nothing in the log to explain it. So it is not "
                    L"started at all.\n\n"
                    L"Install %s, or, if you are porting the "
                    L"addresses yourself: version_check = 0 in tesmioloader.ini, "
                    L"or run the launcher with --ignore-version.",
                    what, SupportedVersionsText(), SupportedVersionsText());

                MessageBoxW(hwnd, text, L"tesmioloader - unsupported game version",
                            MB_ICONERROR | MB_OK);
                SetFocus(g_path);
                return 0;
            }

            SaveConfig(game);

            ShowWindow(hwnd, SW_HIDE);
            if (Inject(game, g_dllFull))
            {
                g_launched = true;
                DestroyWindow(hwnd);
            }
            else
            {
                ShowWindow(hwnd, SW_SHOW);
                MessageBoxW(hwnd, g_log, L"tesmioloader - launch failed",
                            MB_ICONERROR | MB_OK);
            }
            return 0;
        }
        return 0;
    }

    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

// Both of these have to happen before the process touches anything dpi-sensitive
// - the first call that is fixes the awareness for good and SetProcessDPIAware
// then fails - so this runs at the top of wWinMain rather than beside the window
// it is for. Per-monitor v2 when the OS has it, because that is the only mode in
// which a window dragged to a second monitor is redrawn rather than stretched;
// system-wide otherwise.
static void GoDpiAware()
{
    HMODULE u32 = GetModuleHandleW(L"user32.dll");
    if (!u32) return;

    typedef BOOL (WINAPI *SetCtxFn)(HANDLE);
    if (SetCtxFn ctx = (SetCtxFn)GetProcAddress(u32, "SetProcessDpiAwarenessContext"))
        if (ctx((HANDLE)-4))            // DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
            return;

    SetProcessDPIAware();
}

static void DetectDpi()
{
    HDC dc = GetDC(NULL);
    if (!dc) return;
    int dpi = GetDeviceCaps(dc, LOGPIXELSY);
    ReleaseDC(NULL, dc);
    if (dpi >= 96) g_dpi = dpi;
}

static bool ShowWindowUi(const wchar_t* gameFull)
{
    INITCOMMONCONTROLSEX icc = { sizeof(icc), ICC_STANDARD_CLASSES };
    InitCommonControlsEx(&icc);

    {
        NONCLIENTMETRICSW ncm = { sizeof(ncm) };
        if (SystemParametersInfoW(SPI_GETNONCLIENTMETRICS, sizeof(ncm), &ncm, 0))
        {
            // The metrics come back already sized for the system dpi, so only a
            // per-monitor difference is left to apply.
            ncm.lfMessageFont.lfHeight = -MulDiv(9, g_dpi, 72);
            g_font = CreateFontIndirectW(&ncm.lfMessageFont);
        }
    }

    HINSTANCE inst = GetModuleHandleW(NULL);

    // The window's icon is its class's, not the executable's - an exe with an
    // ICON resource gets it in Explorer and on the taskbar and still shows the
    // default in its own title bar unless the class carries one. Both sizes are
    // asked for by hand: the title bar takes the small one and Alt-Tab the
    // large, and letting one be derived from the other is how a logo ends up
    // looking smeared in exactly one of those two places.
    //
    // logo.ico is only there when build.bat found rc.exe. Without it, fall back
    // to what this used to show - the game's own icon.
    HICON iconBig = (HICON)LoadImageW(inst, MAKEINTRESOURCEW(IDI_TSM_LOGO), IMAGE_ICON,
                                      GetSystemMetrics(SM_CXICON),
                                      GetSystemMetrics(SM_CYICON), 0);
    HICON iconSmall = (HICON)LoadImageW(inst, MAKEINTRESOURCEW(IDI_TSM_LOGO), IMAGE_ICON,
                                        GetSystemMetrics(SM_CXSMICON),
                                        GetSystemMetrics(SM_CYSMICON), 0);
    if (!iconBig && gameFull[0])
    {
        iconBig = ExtractIconW(inst, gameFull, 0);
        if (iconBig == (HICON)1) iconBig = NULL;
    }

    WNDCLASSEXW wc = { sizeof(wc) };
    wc.lpfnWndProc   = WndProc;
    wc.hInstance     = inst;
    // UNICODE is not defined here, so MAKEINTRESOURCE in IDC_ARROW is the ANSI one.
    wc.hCursor       = LoadCursorW(NULL, (LPCWSTR)IDC_ARROW);
    wc.hbrBackground = GetSysColorBrush(COLOR_BTNFACE);
    wc.lpszClassName = L"tesmiolauncher";
    wc.hIcon         = iconBig;
    wc.hIconSm       = iconSmall ? iconSmall : iconBig;
    if (!RegisterClassExW(&wc)) { Fail(L"RegisterClassEx"); return false; }

    // The scrolling viewport the plugin checkboxes live in. Its own class
    // because it has its own scroll state and forwards its children's messages;
    // WS_EX_CONTROLPARENT is put on the instance rather than here.
    {
        WNDCLASSEXW lc = { sizeof(lc) };
        lc.lpfnWndProc   = ListProc;
        lc.hInstance     = inst;
        lc.hCursor       = LoadCursorW(NULL, (LPCWSTR)IDC_ARROW);
        lc.hbrBackground = GetSysColorBrush(COLOR_BTNFACE);
        lc.lpszClassName = LIST_CLASS;
        if (!RegisterClassExW(&lc)) { Fail(L"RegisterClassEx(list)"); return false; }
    }

    // 96-dpi layout. Wider than it was because a plugin's label now shares a
    // row with a second one, and every row still has to fit "resources.dll
    // [signed by Tesmio]" without an ellipsis.
    const int W       = 700;
    const int pad     = 12;
    const int rowH    = 22;
    const int btnW    = 92;
    const int btnH    = 26;
    const int lineH   = 16;

    // Rows, then how many of them fit. The count no longer sets the window
    // height: two columns halve it and the rest is scrolled, so a machine with
    // 32 plugins gets the same window as one with two.
    int listRows = (g_plugCount + LIST_COLS - 1) / LIST_COLS;
    if (listRows < 1) listRows = 1;

    int shownRows = listRows < LIST_MAXROW ? listRows : LIST_MAXROW;

    // Everything except the list, in 96-dpi units, so the cap can be lowered
    // again on a screen that would not take even LIST_MAXROW rows.
    const int fixedH = pad + 18 + rowH + pad + lineH + lineH + pad
                     + (18 + rowH + 12) + pad + lineH + pad + btnH + pad;
    {
        RECT frame = { 0, 0, S(W), S(fixedH) };
        AdjustWindowRect(&frame, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU, FALSE);

        RECT work;
        if (SystemParametersInfoW(SPI_GETWORKAREA, 0, &work, 0))
        {
            int room = (work.bottom - work.top) - (frame.bottom - frame.top);
            int fits = room / S(LIST_ROW);
            if (fits < 2) fits = 2;                 // something has to be visible
            if (shownRows > fits) shownRows = fits;
        }
    }

    const int listW   = W - 2 * pad - 24;
    const int listH   = shownRows * LIST_ROW;
    const int groupH  = 18 + rowH + listH + 12;

    int y = pad;
    const int labelY  = y;                      y += 18;
    const int pathY   = y;                      y += rowH + pad;
    const int verReqY = y;                      y += lineH;
    const int verGotY = y;                      y += lineH + pad;
    const int groupY  = y;                      y += groupH + pad;
    const int statusY = y;                      y += lineH + pad;
    const int btnY    = y;                      y += btnH + pad;

    RECT rc = { 0, 0, S(W), S(y) };
    AdjustWindowRect(&rc, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU, FALSE);

    int winW = rc.right - rc.left, winH = rc.bottom - rc.top;
    int cx = (GetSystemMetrics(SM_CXSCREEN) - winW) / 2;
    int cy = (GetSystemMetrics(SM_CYSCREEN) - winH) / 2;

    wchar_t windowTitle[128];
    _snwprintf_s(windowTitle, _countof(windowTitle), _TRUNCATE,
                 L"tesmioloader v. %s", g_version);

    HWND hwnd = CreateWindowExW(WS_EX_CONTROLPARENT, wc.lpszClassName,
                                windowTitle, WS_OVERLAPPED | WS_CAPTION |
                                WS_SYSMENU | WS_MINIMIZEBOX,
                                cx, cy, winW, winH, NULL, NULL, inst, NULL);
    if (!hwnd) { Fail(L"CreateWindowEx"); return false; }

    Child(hwnd, L"STATIC", L"Game executable", 0, pad, labelY, W - 2 * pad, 16, 0);

    g_path = Child(hwnd, L"EDIT", gameFull, WS_BORDER | WS_TABSTOP | ES_AUTOHSCROLL,
                   pad, pathY, W - 2 * pad - btnW - 6, rowH, IDC_PATH);
    Child(hwnd, L"BUTTON", L"Browse...", WS_TABSTOP,
          W - pad - btnW, pathY, btnW, rowH, IDC_BROWSE);

    // Two lines about the version, and the first one never changes: which build
    // this launcher is for has to be readable even when nothing is wrong with
    // the one installed.
    //
    // SS_NOPREFIX on both, or "Workers & Resources" renders as "Workers
    // Resources" with an underlined R - a static treats & as a mnemonic marker
    // unless told not to.
    {
        wchar_t req[192];
        VersionRequirementText(req, _countof(req));
        Child(hwnd, L"STATIC", req, SS_NOPREFIX,
              pad, verReqY, W - 2 * pad, lineH, IDC_VERREQ);
    }
    g_verGot = Child(hwnd, L"STATIC", L"", SS_ENDELLIPSIS | SS_NOPREFIX,
                     pad, verGotY, W - 2 * pad, lineH, IDC_VERGOT);

    // Before g_status exists, so the "game version ..." line this logs stays in
    // the log buffer instead of replacing the status line's "ready".
    RefreshVersionUi();

    // WS_CLIPSIBLINGS, and it is the only control here that has it. A group box
    // paints its whole rectangle, and everything in this group sits inside that
    // rectangle - so without the style it wipes the plugin list on every
    // repaint. The checkboxes inside the list are then still there, still
    // enumerable and still clickable, and invisible until something else
    // invalidates them: they are grandchildren, so the group box painting over
    // their parent never asks them to draw again.
    //
    // The style goes here and nowhere else. It excludes every overlapping
    // sibling from this window's own painting, which is exactly what a
    // container wants and exactly what its contents do not - putting it on the
    // controls as well makes each of them clip the group box out of itself, and
    // the group box's rectangle covers all of them.
    Child(hwnd, L"BUTTON", L"Plugins", BS_GROUPBOX | WS_CLIPSIBLINGS,
          pad, groupY, W - 2 * pad, groupH, 0);

    g_hostBox = Child(hwnd, L"BUTTON", L"Load plugins at all",
                      BS_AUTOCHECKBOX | WS_TABSTOP,
                      pad + 12, groupY + 18, W - 2 * pad - 24, rowH - 2, IDC_HOST);
    SendMessageW(g_hostBox, BM_SETCHECK, g_host ? BST_CHECKED : BST_UNCHECKED, 0);

    g_list = CreateWindowExW(WS_EX_CONTROLPARENT, LIST_CLASS, NULL,
                             WS_CHILD | WS_VISIBLE | WS_VSCROLL,
                             S(pad + 12), S(groupY + 18 + rowH), S(listW), S(listH),
                             hwnd, (HMENU)(INT_PTR)IDC_LIST, inst, NULL);
    if (!g_list) { Fail(L"CreateWindowEx(list)"); return false; }

    // The scroll bar has to be settled before the client width is measured -
    // when it is showing it takes its width out of the client area, and the two
    // columns are laid out in what is left.
    g_listContent = listRows * S(LIST_ROW);
    g_listView    = S(listH);
    g_listPos     = 0;
    ListSetScroll(g_list);

    RECT lr;
    GetClientRect(g_list, &lr);
    const int colW = lr.right / LIST_COLS;

    for (int i = 0; i < g_plugCount; i++)
    {
        PluginEntry* e = &g_plug[i];

        wchar_t note[192];
        PluginNote(e, note, _countof(note), true);

        wchar_t label[256];
        if (note[0])
            _snwprintf_s(label, _countof(label), _TRUNCATE, L"%s  [%s]", e->file, note);
        else
            wcscpy_s(label, _countof(label), e->file);

        // Row-major: 0 and 1 share the top row, 2 and 3 the next. Filling one
        // column and then the other would read better in a list that never
        // scrolls, but here the two halves would slide past each other.
        int col = i % LIST_COLS;
        int row = i / LIST_COLS;

        // BS_NOTIFY, or a button never sends BN_SETFOCUS at all and ListReveal
        // is dead code - tab traversal would then park the focus on a row
        // scrolled out of sight.
        e->box = ChildPx(g_list, L"BUTTON", label,
                         BS_AUTOCHECKBOX | BS_NOTIFY | WS_TABSTOP,
                         col * colW, row * S(LIST_ROW), colW - S(6), S(18),
                         IDC_PLUGIN0 + i);
        SendMessageW(e->box, BM_SETCHECK, e->on ? BST_CHECKED : BST_UNCHECKED, 0);
    }
    if (!g_plugCount)
        ChildPx(g_list, L"STATIC", L"none found - is build\\plugins\\ there?", 0,
                0, 0, lr.right, S(18), 0);

    SyncPluginBoxes();

    // SS_NOPREFIX here too: the status line carries paths, and a folder with an
    // & in its name would lose it.
    g_status = Child(hwnd, L"STATIC", gameFull[0] ? L"ready" : L"game not found - browse for it",
                     SS_PATHELLIPSIS | SS_NOPREFIX, pad, statusY, W - 2 * pad, lineH, IDC_STATUS);

    Child(hwnd, L"BUTTON", L"Launch", BS_DEFPUSHBUTTON | WS_TABSTOP,
          W - pad - 2 * btnW - 6, btnY, btnW, btnH, IDC_LAUNCH);
    Child(hwnd, L"BUTTON", L"Close", WS_TABSTOP,
          W - pad - btnW, btnY, btnW, btnH, IDC_CLOSE);

    ShowWindow(hwnd, SW_SHOW);
    SetFocus(gameFull[0] ? GetDlgItem(hwnd, IDC_LAUNCH) : g_path);

    MSG m;
    while (GetMessageW(&m, NULL, 0, 0) > 0)
    {
        // Gives tab traversal, space on a checkbox, Enter on Launch and Escape
        // on Close without any of it being written here.
        if (!IsDialogMessageW(hwnd, &m)) { TranslateMessage(&m); DispatchMessageW(&m); }
    }

    g_status = NULL;
    return g_launched;
}

// ---------------------------------------------------------------- entry

int APIENTRY wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int)
{
    GoDpiAware();
    DetectDpi();
    OpenConsole();

    int argc = 0;
    wchar_t** argv = CommandLineToArgvW(GetCommandLineW(), &argc);

    wchar_t selfDir[MAX_PATH];
    GetModuleFileNameW(NULL, selfDir, MAX_PATH);
    ToParent(selfDir);

    wchar_t game[MAX_PATH] = {0};
    wchar_t dll[MAX_PATH]  = {0};
    bool    gui            = true;
    bool    findOnly       = false;
    bool    ignoreVersion  = false;

    // wcscpy_s calls the invalid-parameter handler when the source does not
    // fit, and the default handler TERMINATES the process - so a --game with a
    // path longer than MAX_PATH used to kill the launcher outright instead of
    // reporting anything. Truncation is refused explicitly and said out loud.
    #define TSM_ARG_COPY(dst, src, what)                                        \
        do {                                                                    \
            if (wcslen(src) >= MAX_PATH)                                        \
                Msg(L"%s path is longer than %d characters - ignored",          \
                    what, MAX_PATH - 1);                                        \
            else                                                                \
                wcscpy_s(dst, MAX_PATH, src);                                   \
        } while (0)

    for (int i = 1; argv && i < argc; i++)
    {
        if (!_wcsicmp(argv[i], L"--game") && i + 1 < argc) TSM_ARG_COPY(game, argv[++i], L"--game");
        else if (!_wcsicmp(argv[i], L"--dll") && i + 1 < argc) TSM_ARG_COPY(dll, argv[++i], L"--dll");
        else if (!_wcsicmp(argv[i], L"--nogui")) gui = false;
        else if (!_wcsicmp(argv[i], L"--find")) { findOnly = true; gui = false; }
        else if (!_wcsicmp(argv[i], L"--ignore-version")) ignoreVersion = true;
        else if (!_wcsicmp(argv[i], L"--help"))
        {
            Msg(L"usage: tesmiolauncher [--game <SOVIET64.exe|folder>] "
                L"[--dll <tesmioloader.dll>] [--nogui] [--find] [--ignore-version]");
            Msg(L"  no --game: the ini's game_exe, then a walk up from here, then Steam");
            Msg(L"  --nogui:   skip the window, launch with whatever is in the ini");
            Msg(L"  --find:    say what the search resolved and exit, changing nothing");
            Msg(L"  --ignore-version: inject into a game that is not %s"
                L". It will probably not work", SupportedVersionsText());
            if (!g_console) MessageBoxW(NULL, g_log, L"tesmiolauncher", MB_OK);
            LocalFree(argv);
            return 0;
        }
    }

    #undef TSM_ARG_COPY

    // Nothing below reads argv again.
    if (argv) { LocalFree(argv); argv = NULL; }

    // --- the DLL. Its folder is what decides which ini both halves read.
    if (!dll[0])
    {
        Join(dll, MAX_PATH, selfDir, LOADER_DLL);
        if (!Exists(dll)) Join(dll, MAX_PATH, selfDir, L"build\\" LOADER_DLL);
    }
    if (!GetFullPathNameW(dll, MAX_PATH, g_dllFull, NULL))
    {
        Fail(L"GetFullPathName(dll)");
        return 1;
    }

    wchar_t dllDir[MAX_PATH];
    wcscpy_s(dllDir, MAX_PATH, g_dllFull);
    ToParent(dllDir);
    SetIniPath(dllDir);
    ReadConfig();

    // After ReadConfig, so the flag wins over the ini rather than the other way
    // round - it is the more deliberate of the two.
    if (ignoreVersion) g_versionCheck = false;
    if (!g_versionCheck) Msg(L"version check off - any build will be injected into");

    ScanPlugins(dllDir);

    // --- the game, in order of how much the user meant it.
    wchar_t found[MAX_PATH] = {0};

    if (game[0])
    {
        wchar_t full[MAX_PATH];
        if (GetFullPathNameW(game, MAX_PATH, full, NULL))
        {
            if (DirExists(full))      IsGameDir(full, found, MAX_PATH);
            else if (Exists(full))    wcscpy_s(found, MAX_PATH, full);
        }
        if (!found[0]) Msg(L"--game %s is not there", game);
    }

    if (!found[0])
    {
        wchar_t saved[MAX_PATH] = {0};
        GetPrivateProfileStringW(L"tesmioloader", L"game_exe", L"",
                                 saved, _countof(saved), g_ini);
        if (saved[0] && Exists(saved)) { wcscpy_s(found, MAX_PATH, saved); Msg(L"game_exe from the ini"); }
    }

    if (!found[0] && FindNearSelf(selfDir, found, MAX_PATH))
        Msg(L"found by walking up from %s", selfDir);

    if (!found[0] && FindViaSteam(found, MAX_PATH))
        Msg(L"found through Steam");

    // Nothing written, nothing started - the only way to see what the four
    // strategies resolved to, since the winner is the only one that leaves a
    // trace once the game is running.
    if (findOnly)
    {
        Msg(L"dpi    %d", g_dpi);
        Msg(L"ini    %s", g_ini);
        Msg(L"dll    %s%s", g_dllFull, Exists(g_dllFull) ? L"" : L"   (missing)");
        for (int i = 0; i < g_plugCount; i++)
        {
            wchar_t note[192];
            PluginNote(&g_plug[i], note, _countof(note), false);
            if (note[0])
                Msg(L"plugin %-20s %-3s   [%s]", g_plug[i].file,
                    g_plug[i].on ? L"on" : L"off", note);
            else
                Msg(L"plugin %-20s %s", g_plug[i].file,
                    g_plug[i].on ? L"on" : L"off");
        }
        Msg(L"api    %u..%u", TSM_API_VERSION_MIN, TSM_API_VERSION);
        Msg(L"game   %s", found[0] ? found : L"NOT FOUND");

        // Not "where" but "what", and the only line here that can veto the
        // rest: --find exits 2 when the game it found would not be launched.
        // GameVersionOf prints what it read; this says what was wanted.
        for (size_t i = 0; i < GAME_VER_COUNT; i++)
            Msg(L"needs  v%s (build %08X)", kSupportedVersions[i].text,
                kSupportedVersions[i].stamp);
        if (found[0] && VersionRefuses(GameVersionOf(found))) return 2;
        return found[0] ? 0 : 1;
    }

    if (!Exists(g_dllFull))
    {
        Msg(L"dll not found: %s", g_dllFull);
        if (gui) MessageBoxW(NULL, g_log, L"tesmioloader", MB_ICONERROR | MB_OK);
        return 1;
    }

    if (gui) return ShowWindowUi(found) ? 0 : 1;

    if (!found[0])
    {
        Msg(L"%s not found. Pass --game, or run without --nogui and browse for it.", GAME_EXE);
        return 1;
    }

    // The same gate the window applies, because --nogui is the same launch with
    // nobody watching - a script that starts the game after an update must fail
    // here rather than inject into a build none of the addresses fit.
    if (VersionRefuses(GameVersionOf(found)))
    {
        Msg(L"this game is not %s - refusing to inject. "
            L"version_check = 0 in %s, or --ignore-version, overrides this.",
            SupportedVersionsText(), g_ini);
        return 2;
    }

    SaveConfig(found);
    return Inject(found, g_dllFull) ? 0 : 1;
}
